### ISSUE TITLE
Rust isn't included

### ISSUE THREAD

**Issue by CorruptComputer** [yaph/programming-languages-influence#2]
Also it seems that freebase has been deprecated.

**Comment by yaph** [comment]
Yes, Freebase is not updated any longer and Rust is not included in the data. I started work on a wikipedia based solution, but this is on a hiatus.

**Comment by CorruptComputer** [comment]
Could you get the data from GitHub? 
![screenshot_20161226-083030_01](https://cloud.githubusercontent.com/assets/5573038/21482717/bdf72950-cb45-11e6-8ea0-ae188cca3c30.png)

**Comment by yaph** [comment]
It is possible to create a network based on GitHub language relations, but the influence relations that were in Freebase are not mapped on GitHub.

**Comment by CorruptComputer** [comment]
You could look at what is usually used in the same repos, like how this one uses shell and python.

**Comment by yaph** [comment]
Certainly interesting to see what languages co-occur in GitHub repos, but this would really be a different project. For example, in a GitHub graph JavaScript would be way more prominent than Lisp, whereas Lisp is more influential in terms of language semantics.

You can query the GitHub data via Google's Big Query service. [Here's more info](https://cloud.google.com/bigquery/public-data/github) if you want to take a stab at it.
